dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: java-sample-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: sample-app-gradle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: sample-app-php
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
